#!/usr/bin/env python3
"""Materialize the active paper's generated LaTeX inputs.

The active manuscript uses short paths such as ``stata_output/tab_pooled_itt``
and ``structural_output/tab_counterfactuals.tex``. This script reads the
manuscript, finds the generated inputs and figures it actually references, and
copies the corresponding artifacts from the analysis output folders into the
repo-root LaTeX input folders.

This writes only inside the repository. The `reading-groups-struc` repository is
the Overleaf-linked project, so no external Dropbox/Apps mirror is needed.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANUSCRIPT = (
    REPO_ROOT / "main_3country_new.tex"
    if (REPO_ROOT / "main_3country_new.tex").exists()
    else REPO_ROOT / "main_3country_new.structural_edit.tex"
)
STATA_SOURCE_DIR = REPO_ROOT / "4_Stata2" / "output"
STRUCTURAL_LATEX_SOURCE_DIR = (
    REPO_ROOT / "3_Python" / "output" / "structural_smm" / "latex"
)
STRUCTURAL_FIG_SOURCE_DIR = REPO_ROOT / "3_Python" / "output" / "structural_smm"
STRUCTURAL_PAPER_DIR = REPO_ROOT / "structural_output"
REPORT_PATH = REPO_ROOT / "paper_pipeline" / "materialize_report.json"
MANIFEST_PATH = REPO_ROOT / "paper_pipeline" / "active_inputs_manifest.csv"
STALE_ARCHIVE_DIR = REPO_ROOT / "archive" / "stale_paper_inputs"


@dataclass
class Artifact:
    kind: str
    manuscript_path: str
    source_path: str
    repo_target: str
    generator: str
    status: str = "pending"
    sha256: str | None = None
    note: str = ""


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def tex_with_suffix(path_text: str) -> str:
    return path_text if Path(path_text).suffix else f"{path_text}.tex"


def read_references(manuscript: Path) -> tuple[list[str], list[str]]:
    text = manuscript.read_text(encoding="utf-8")
    inputs = re.findall(r"\\input\{([^}]+)\}", text)
    figures = re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", text)
    return inputs, figures


def source_for_reference(ref: str, kind: str) -> tuple[Path, Path, str, str]:
    ref_with_suffix = tex_with_suffix(ref) if kind == "table" else ref
    target = REPO_ROOT / ref_with_suffix

    if ref.startswith("stata_output/"):
        source = STATA_SOURCE_DIR / Path(ref_with_suffix).name
        generator = "4_Stata2 pipeline; see paper_pipeline/README.md"
        note = "Stata manuscript table"
    elif ref.startswith("structural_output/") and kind == "table":
        source = STRUCTURAL_LATEX_SOURCE_DIR / Path(ref_with_suffix).name
        generator = "3_Python/structural_blockwise_redesign.py"
        note = "Structural LaTeX table"
    elif ref.startswith("structural_output/") and kind == "figure":
        name = Path(ref).name
        candidate = STRUCTURAL_FIG_SOURCE_DIR / name
        if candidate.exists():
            source = candidate
            generator = "3_Python/structural_blockwise_redesign.py"
        else:
            source = STRUCTURAL_PAPER_DIR / name
            generator = "3_Python/make_paper_summary_figures.py"
        note = "Structural or paper-summary figure"
    else:
        source = REPO_ROOT / ref_with_suffix
        generator = "Not generated by the active paper pipeline"
        note = "Non-pipeline input"

    return source, target, generator, note


def collect_artifacts(manuscript: Path) -> list[Artifact]:
    inputs, figures = read_references(manuscript)
    artifacts: list[Artifact] = []

    for ref in inputs:
        if not (ref.startswith("stata_output/") or ref.startswith("structural_output/")):
            continue
        source, target, generator, note = source_for_reference(ref, "table")
        artifacts.append(
            Artifact(
                kind="table",
                manuscript_path=tex_with_suffix(ref),
                source_path=str(source.relative_to(REPO_ROOT)),
                repo_target=str(target.relative_to(REPO_ROOT)),
                generator=generator,
                note=note,
            )
        )

    for ref in figures:
        if not ref.startswith("structural_output/"):
            continue
        source, target, generator, note = source_for_reference(ref, "figure")
        artifacts.append(
            Artifact(
                kind="figure",
                manuscript_path=ref,
                source_path=str(source.relative_to(REPO_ROOT)),
                repo_target=str(target.relative_to(REPO_ROOT)),
                generator=generator,
                note=note,
            )
        )

    return artifacts


def copy_artifact(artifact: Artifact, check_only: bool) -> Artifact:
    source = REPO_ROOT / artifact.source_path
    target = REPO_ROOT / artifact.repo_target

    if not source.exists():
        artifact.status = "missing_source"
        return artifact

    artifact.sha256 = sha256(source)
    if check_only:
        artifact.status = "present" if target.exists() else "would_create"
        if target.exists() and sha256(target) != artifact.sha256:
            artifact.status = "would_update"
        return artifact

    target.parent.mkdir(parents=True, exist_ok=True)
    if source.resolve() != target.resolve():
        shutil.copy2(source, target)
    artifact.status = "materialized"
    return artifact


def write_manifest(artifacts: list[Artifact]) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    with MANIFEST_PATH.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "kind",
                "manuscript_path",
                "source_path",
                "repo_target",
                "generator",
                "status",
                "sha256",
                "note",
            ],
        )
        writer.writeheader()
        for artifact in artifacts:
            writer.writerow(asdict(artifact))


def archive_stale_outputs(
    artifacts: list[Artifact],
    folder_name: str,
    check_only: bool,
    keep_stale: bool,
) -> list[dict[str, str]]:
    """Move unreferenced paper-facing outputs out of active LaTeX folders."""
    folder = REPO_ROOT / folder_name
    if not folder.exists():
        return []

    active_names = {
        Path(artifact.repo_target).name
        for artifact in artifacts
        if Path(artifact.repo_target).parts and Path(artifact.repo_target).parts[0] == folder_name
    }
    stale_paths = sorted(
        path for path in folder.iterdir() if path.is_file() and path.name not in active_names
    )

    archived: list[dict[str, str]] = []
    for stale_path in stale_paths:
        destination = STALE_ARCHIVE_DIR / folder_name / stale_path.name
        archived.append(
            {
                "path": str(stale_path.relative_to(REPO_ROOT)),
                "archive_path": str(destination.relative_to(REPO_ROOT)),
                "status": "kept" if keep_stale else "would_archive" if check_only else "archived",
            }
        )
        if check_only or keep_stale:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists():
            destination.unlink()
        shutil.move(str(stale_path), str(destination))

    return archived


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manuscript", type=Path, default=DEFAULT_MANUSCRIPT)
    parser.add_argument("--check-only", action="store_true")
    parser.add_argument(
        "--keep-stale",
        action="store_true",
        help="Report but do not archive unreferenced paper-facing outputs.",
    )
    args = parser.parse_args()

    manuscript = args.manuscript.resolve()
    if not manuscript.exists():
        raise FileNotFoundError(f"Missing manuscript: {manuscript}")

    artifacts = collect_artifacts(manuscript)
    missing: list[str] = []

    for artifact in artifacts:
        copy_artifact(artifact, args.check_only)
        if artifact.status == "missing_source":
            missing.append(artifact.source_path)

    archived_stale = []
    archived_stale.extend(
        archive_stale_outputs(artifacts, "stata_output", args.check_only, args.keep_stale)
    )
    archived_stale.extend(
        archive_stale_outputs(
            artifacts, "structural_output", args.check_only, args.keep_stale
        )
    )

    write_manifest(artifacts)

    report = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "manuscript": str(manuscript),
        "check_only": args.check_only,
        "keep_stale": args.keep_stale,
        "artifact_count": len(artifacts),
        "missing_source_count": len(missing),
        "missing_sources": missing,
        "stale_file_count": len(archived_stale),
        "stale_files": archived_stale,
        "manifest": str(MANIFEST_PATH),
        "artifacts": [asdict(artifact) for artifact in artifacts],
    }
    REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(
        f"Materialization {'check' if args.check_only else 'run'}: "
        f"{len(artifacts)} artifacts, {len(missing)} missing sources."
    )
    if archived_stale:
        action = "kept" if args.keep_stale else "would archive" if args.check_only else "archived"
        print(f"Stale paper-facing outputs {action}: {len(archived_stale)}.")
        for item in archived_stale:
            print(f"Stale output: {item['path']} -> {item['archive_path']}")
    print(f"Manifest: {MANIFEST_PATH}")
    print(f"Report: {REPORT_PATH}")
    if missing:
        for path in missing:
            print(f"Missing source: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
